baseURL = 'https://hugo-staging.up.railway.app/'
languageCode = 'en-us'
title = 'Jitachi Development'
theme = 'blank'

[Menu]
 [[menu.Main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 1