baseURL = 'https://hugo-staging.up.railway.app/'
languageCode = 'en-us'
title = 'Jitachi Development'
theme = 'blank'

[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
  block = true
  title = true

[markup.goldmark.renderer]
  unsafe = true