baseURL = 'https://jitachi.up.railway.app/'
languageCode = 'en-us'
title = 'Jitachi Garcia'
theme = 'blank'

[Menu]
 [[menu.Main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2